version: '3'
services:
  web_neda:
    container_name: "web_neda"
    ports:
      - 122:8080
    build:
      dockerfile: ./Dockerfile
      context: .
    volumes:
      - ./web_neda/testtt.csv:/code/testtt.csv
      - ./web_neda/substationsPowesAlti.csv:/code/substationsPowesAlti.csv
      - ./web_neda/power_curves.csv:/code/power_curves.csv
      - ./web_neda/ex-substations.geojson:/code/ex-substations.geojson
      - ./web_neda/existing-transmission-lines.geojson:/code/existing-transmission-lines.geojson

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl_cert/fullchain.pem:/etc/nginx/ssl/codewithneda.crt
      - ./ssl_cert/privkey.pem:/etc/nginx/ssl/codewithneda.key

    ports:
      - 80:80
      - 443:443
    depends_on:
      - web_neda
    