version: '3'
services:
  web_neda:
    container_name: "web_neda"
    ports:
      - 122:8080
    build:
      dockerfile: ./Dockerfile
      context: .
    volumes:
      - ./testtt.csv:/code/testtt.csv
      - ./substationsPowesAlti.csv:/code/substationsPowesAlti.csv
      - ./power_curves.csv:/code/power_curves.csv
      - ./ex-substations.geojson:/code/ex-substations.geojson
      - ./existing-transmission-lines.geojson:/code/existing-transmission-lines.geojson
    deploy:
      resources:
        limits:
          cpus: '0.99'  # Use half of available CPU cores
          memory: '16G'  # Use 2 GB of RAM changes from flori

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl_cert/fullchain.pem:/etc/nginx/ssl/codewithneda.crt
      - ./ssl_cert/privkey.pem:/etc/nginx/ssl/codewithneda.key
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web_neda
