name: Deploy to PROD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and Deploy
        run: |
          cd /home/actions-runner/prod/wind/wind
          mv ./testtt.csv ./small_testtt.csv
          cp /home/big_testtt.csv ./testtt.csv
          sudo docker-compose up --build -d